"""empty message

Revision ID: 1912981ceef1
Revises: e36bf0625d1e
Create Date: 2024-08-08 18:02:15.363418

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1912981ceef1"
down_revision: Union[str, None] = "e36bf0625d1e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_blog_post_id", table_name="blog_post")
    op.drop_index("ix_blog_post_is_deleted", table_name="blog_post")
    op.drop_index("ix_blog_post_user_id", table_name="blog_post")
    op.drop_table("blog_post")
    op.add_column(
        "ms_artist",
        sa.Column(
            "apple_artist_link",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
        ),
    )
    op.add_column(
        "ms_artist",
        sa.Column(
            "beatport_artist_link",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
        ),
    )
    op.add_column(
        "ms_artist",
        sa.Column(
            "deezer_artist_link",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
        ),
    )
    op.add_column(
        "ms_artist",
        sa.Column(
            "tidal_artist_link",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
        ),
    )
    op.add_column(
        "ms_artist",
        sa.Column(
            "pandora_artist_link",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
        ),
    )
    op.add_column(
        "ms_artist",
        sa.Column(
            "shazam_artist_link",
            sqlmodel.sql.sqltypes.AutoString(length=255),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ms_artist", "shazam_artist_link")
    op.drop_column("ms_artist", "pandora_artist_link")
    op.drop_column("ms_artist", "tidal_artist_link")
    op.drop_column("ms_artist", "deezer_artist_link")
    op.drop_column("ms_artist", "beatport_artist_link")
    op.drop_column("ms_artist", "apple_artist_link")
    op.create_table(
        "blog_post",
        sa.Column(
            "deleted_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("is_deleted", sa.BOOLEAN(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "media_url", sa.VARCHAR(length=255), autoincrement=False, nullable=True
        ),
        sa.Column("title", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column(
            "text", sa.VARCHAR(length=63206), autoincrement=False, nullable=False
        ),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"], ["admin_user.id"], name="fk_blog_post_user_id_admin_user"
        ),
        sa.PrimaryKeyConstraint("id", name="pk_blog_post"),
        comment="Blog post information",
    )
    op.create_index("ix_blog_post_user_id", "blog_post", ["user_id"], unique=False)
    op.create_index(
        "ix_blog_post_is_deleted", "blog_post", ["is_deleted"], unique=False
    )
    op.create_index("ix_blog_post_id", "blog_post", ["id"], unique=False)
    # ### end Alembic commands ###
