"""empty message

Revision ID: cda4ac6fa060
Revises: c1c6ea23f7a5
Create Date: 2024-08-05 21:21:21.965605

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "cda4ac6fa060"
down_revision: Union[str, None] = "c1c6ea23f7a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ms_artist",
        sa.Column(
            "clerk_org_id", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
    )
    op.add_column(
        "ms_artist", sa.Column("soundcharts_artist_id", sa.Uuid(), nullable=False)
    )
    op.drop_index("ix_ms_artist_user_id", table_name="ms_artist")
    op.drop_constraint("uq_ms_artist_org_id", "ms_artist", type_="unique")
    op.drop_constraint("uq_ms_artist_soundcharts_id", "ms_artist", type_="unique")
    op.create_unique_constraint(None, "ms_artist", ["clerk_org_id"])
    op.create_unique_constraint(None, "ms_artist", ["soundcharts_artist_id"])
    op.drop_constraint(
        "fk_ms_artist_user_id_admin_user", "ms_artist", type_="foreignkey"
    )
    op.drop_column("ms_artist", "user_id")
    op.drop_column("ms_artist", "soundcharts_id")
    op.drop_column("ms_artist", "org_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ms_artist",
        sa.Column("org_id", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "ms_artist",
        sa.Column("soundcharts_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "ms_artist",
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
    )
    op.create_foreign_key(
        "fk_ms_artist_user_id_admin_user",
        "ms_artist",
        "admin_user",
        ["user_id"],
        ["id"],
    )
    op.drop_constraint(None, "ms_artist", type_="unique")
    op.drop_constraint(None, "ms_artist", type_="unique")
    op.create_unique_constraint(
        "uq_ms_artist_soundcharts_id", "ms_artist", ["soundcharts_id"]
    )
    op.create_unique_constraint("uq_ms_artist_org_id", "ms_artist", ["org_id"])
    op.create_index("ix_ms_artist_user_id", "ms_artist", ["user_id"], unique=False)
    op.drop_column("ms_artist", "soundcharts_artist_id")
    op.drop_column("ms_artist", "clerk_org_id")
    # ### end Alembic commands ###
