"""empty message

Revision ID: c1c6ea23f7a5
Revises: 2bcc2a7dae9f
Create Date: 2024-08-05 21:14:11.338056

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "c1c6ea23f7a5"
down_revision: Union[str, None] = "2bcc2a7dae9f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ms_artist", sa.Column("soundcharts_id", sa.Uuid(), nullable=False))
    op.create_unique_constraint(None, "ms_artist", ["soundcharts_id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "ms_artist", type_="unique")
    op.drop_column("ms_artist", "soundcharts_id")
    # ### end Alembic commands ###
