"""empty message

Revision ID: 6254cca2aae7
Revises: e36bf0625d1e
Create Date: 2024-08-08 14:19:32.524080

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6254cca2aae7"
down_revision: Union[str, None] = "e36bf0625d1e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ms_artist", "bandsintown_profile_link")
    op.drop_column("ms_artist", "soundcloud_profile_link")
    op.drop_column("ms_artist", "songkick_profile_link")
    op.drop_column("ms_artist", "facebook_profile_link")
    op.drop_column("ms_artist", "instagram_profile_link")
    op.drop_column("ms_artist", "youtube_channel_link")
    op.drop_column("ms_artist", "x_profile_link")
    op.drop_column("ms_artist", "tiktok_profile_link")
    op.drop_column("ms_artist", "spotify_artist_link")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "ms_artist",
        sa.Column(
            "spotify_artist_link",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "ms_artist",
        sa.Column(
            "tiktok_profile_link",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "ms_artist",
        sa.Column(
            "x_profile_link",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "ms_artist",
        sa.Column(
            "youtube_channel_link",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "ms_artist",
        sa.Column(
            "instagram_profile_link",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "ms_artist",
        sa.Column(
            "facebook_profile_link",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "ms_artist",
        sa.Column(
            "songkick_profile_link",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "ms_artist",
        sa.Column(
            "soundcloud_profile_link",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "ms_artist",
        sa.Column(
            "bandsintown_profile_link",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
    )
    # ### end Alembic commands ###
