// This file is auto-generated by @hey-api/openapi-ts

export const $ArtistCreate = {
	properties: {
		media_url: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255
				},
				{
					type: 'null'
				}
			]
		},
		soundcharts_artist_id: {
			type: 'string',
			format: 'uuid'
		},
		email: {
			type: 'string',
			maxLength: 255
		},
		biography: {
			type: 'string',
			maxLength: 1000
		},
		apple_artist_link: {
			type: 'string',
			maxLength: 255,
			default: ''
		},
		beatport_artist_link: {
			type: 'string',
			maxLength: 255,
			default: ''
		},
		deezer_artist_link: {
			type: 'string',
			maxLength: 255,
			default: ''
		},
		tidal_artist_link: {
			type: 'string',
			maxLength: 255,
			default: ''
		},
		pandora_artist_link: {
			type: 'string',
			maxLength: 255,
			default: ''
		},
		shazam_artist_link: {
			type: 'string',
			maxLength: 255,
			default: ''
		},
		spotify_artist_link: {
			type: 'string',
			maxLength: 255,
			default: ''
		},
		youtube_channel_link: {
			type: 'string',
			maxLength: 255,
			default: ''
		},
		instagram_profile_link: {
			type: 'string',
			maxLength: 255,
			default: ''
		},
		facebook_profile_link: {
			type: 'string',
			maxLength: 255,
			default: ''
		},
		x_profile_link: {
			type: 'string',
			maxLength: 255,
			default: ''
		},
		tiktok_profile_link: {
			type: 'string',
			maxLength: 255,
			default: ''
		},
		soundcloud_profile_link: {
			type: 'string',
			maxLength: 255,
			default: ''
		},
		songkick_profile_link: {
			type: 'string',
			maxLength: 255,
			default: ''
		},
		bandsintown_profile_link: {
			type: 'string',
			maxLength: 255,
			default: ''
		}
	},
	additionalProperties: false,
	type: 'object',
	required: ['email', 'biography']
} as const;

export const $ArtistRead = {
	properties: {
		created_at: {
			anyOf: [
				{
					type: 'string'
				},
				{
					type: 'null'
				}
			]
		},
		updated_at: {
			anyOf: [
				{
					type: 'string'
				},
				{
					type: 'null'
				}
			]
		},
		org_id: {
			type: 'string',
			maxLength: 255
		},
		id: {
			type: 'string',
			format: 'uuid'
		},
		media_url: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255
				},
				{
					type: 'null'
				}
			]
		},
		soundcharts_artist_id: {
			type: 'string',
			format: 'uuid'
		},
		email: {
			type: 'string',
			maxLength: 255
		},
		biography: {
			type: 'string',
			maxLength: 1000
		},
		apple_artist_link: {
			type: 'string',
			maxLength: 255,
			default: ''
		},
		beatport_artist_link: {
			type: 'string',
			maxLength: 255,
			default: ''
		},
		deezer_artist_link: {
			type: 'string',
			maxLength: 255,
			default: ''
		},
		tidal_artist_link: {
			type: 'string',
			maxLength: 255,
			default: ''
		},
		pandora_artist_link: {
			type: 'string',
			maxLength: 255,
			default: ''
		},
		shazam_artist_link: {
			type: 'string',
			maxLength: 255,
			default: ''
		},
		spotify_artist_link: {
			type: 'string',
			maxLength: 255,
			default: ''
		},
		youtube_channel_link: {
			type: 'string',
			maxLength: 255,
			default: ''
		},
		instagram_profile_link: {
			type: 'string',
			maxLength: 255,
			default: ''
		},
		facebook_profile_link: {
			type: 'string',
			maxLength: 255,
			default: ''
		},
		x_profile_link: {
			type: 'string',
			maxLength: 255,
			default: ''
		},
		tiktok_profile_link: {
			type: 'string',
			maxLength: 255,
			default: ''
		},
		soundcloud_profile_link: {
			type: 'string',
			maxLength: 255,
			default: ''
		},
		songkick_profile_link: {
			type: 'string',
			maxLength: 255,
			default: ''
		},
		bandsintown_profile_link: {
			type: 'string',
			maxLength: 255,
			default: ''
		}
	},
	type: 'object',
	required: ['org_id', 'email', 'biography']
} as const;

export const $ArtistUpdate = {
	properties: {
		media_url: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255
				},
				{
					type: 'null'
				}
			]
		},
		soundcharts_artist_id: {
			anyOf: [
				{
					type: 'string',
					format: 'uuid'
				},
				{
					type: 'null'
				}
			]
		},
		email: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255
				},
				{
					type: 'null'
				}
			]
		},
		biography: {
			anyOf: [
				{
					type: 'string',
					maxLength: 1000
				},
				{
					type: 'null'
				}
			]
		},
		apple_artist_link: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255
				},
				{
					type: 'null'
				}
			]
		},
		beatport_artist_link: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255
				},
				{
					type: 'null'
				}
			]
		},
		deezer_artist_link: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255
				},
				{
					type: 'null'
				}
			]
		},
		tidal_artist_link: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255
				},
				{
					type: 'null'
				}
			]
		},
		pandora_artist_link: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255
				},
				{
					type: 'null'
				}
			]
		},
		shazam_artist_link: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255
				},
				{
					type: 'null'
				}
			]
		},
		spotify_artist_link: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255
				},
				{
					type: 'null'
				}
			]
		},
		youtube_channel_link: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255
				},
				{
					type: 'null'
				}
			]
		},
		instagram_profile_link: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255
				},
				{
					type: 'null'
				}
			]
		},
		facebook_profile_link: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255
				},
				{
					type: 'null'
				}
			]
		},
		x_profile_link: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255
				},
				{
					type: 'null'
				}
			]
		},
		tiktok_profile_link: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255
				},
				{
					type: 'null'
				}
			]
		},
		soundcloud_profile_link: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255
				},
				{
					type: 'null'
				}
			]
		},
		songkick_profile_link: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255
				},
				{
					type: 'null'
				}
			]
		},
		bandsintown_profile_link: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255
				},
				{
					type: 'null'
				}
			]
		}
	},
	additionalProperties: false,
	type: 'object'
} as const;

export const $Body_login_for_access_token_v1_system_auth_login_post = {
	properties: {
		grant_type: {
			type: 'string',
			pattern: 'password'
		},
		username: {
			type: 'string'
		},
		password: {
			type: 'string'
		},
		scope: {
			type: 'string',
			default: ''
		},
		client_id: {
			anyOf: [
				{
					type: 'string'
				},
				{
					type: 'null'
				}
			]
		},
		client_secret: {
			anyOf: [
				{
					type: 'string'
				},
				{
					type: 'null'
				}
			]
		}
	},
	type: 'object',
	required: ['grant_type', 'username', 'password']
} as const;

export const $GenreCreate = {
	properties: {
		genre_name: {
			type: 'string',
			maxLength: 255,
			examples: ['Electronic']
		}
	},
	additionalProperties: false,
	type: 'object',
	required: ['genre_name']
} as const;

export const $GenreUpdate = {
	properties: {
		genre_name: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255
				},
				{
					type: 'null'
				}
			],
			examples: ['Electronic']
		}
	},
	additionalProperties: false,
	type: 'object'
} as const;

export const $HTTPValidationError = {
	properties: {
		detail: {
			items: {
				$ref: '#/components/schemas/ValidationError'
			},
			type: 'array'
		}
	},
	type: 'object'
} as const;

export const $LabelCreate = {
	properties: {
		label_name: {
			type: 'string',
			maxLength: 255,
			examples: ['Electronic']
		},
		email: {
			type: 'string',
			maxLength: 255,
			examples: ['info@label.com']
		},
		biography: {
			type: 'string',
			maxLength: 1000,
			examples: ['This is the biography of the label.']
		},
		established_year: {
			type: 'integer',
			examples: [1990]
		}
	},
	additionalProperties: false,
	type: 'object',
	required: ['label_name', 'email', 'biography', 'established_year']
} as const;

export const $LabelUpdate = {
	properties: {
		label_name: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255
				},
				{
					type: 'null'
				}
			],
			examples: ['Electronic']
		},
		email: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255
				},
				{
					type: 'null'
				}
			],
			examples: ['info@label.com']
		},
		biography: {
			anyOf: [
				{
					type: 'string',
					maxLength: 1000
				},
				{
					type: 'null'
				}
			],
			examples: ['This is the biography of the label.']
		},
		established_year: {
			anyOf: [
				{
					type: 'integer'
				},
				{
					type: 'null'
				}
			],
			examples: [1990]
		}
	},
	additionalProperties: false,
	type: 'object'
} as const;

export const $ReleaseCreate = {
	properties: {
		release_name: {
			type: 'string',
			maxLength: 255,
			examples: ['Electronic']
		}
	},
	additionalProperties: false,
	type: 'object',
	required: ['release_name']
} as const;

export const $ReleaseUpdate = {
	properties: {
		release_name: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255
				},
				{
					type: 'null'
				}
			],
			examples: ['Electronic']
		}
	},
	additionalProperties: false,
	type: 'object'
} as const;

export const $SubgenreCreate = {
	properties: {
		subgenre_name: {
			type: 'string',
			maxLength: 255,
			examples: ['Minimal Techno']
		}
	},
	additionalProperties: false,
	type: 'object',
	required: ['subgenre_name']
} as const;

export const $SubgenreUpdate = {
	properties: {
		subgenre_name: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255
				},
				{
					type: 'null'
				}
			],
			examples: ['Minimal Techno']
		}
	},
	additionalProperties: false,
	type: 'object'
} as const;

export const $Token = {
	properties: {
		access_token: {
			type: 'string'
		},
		token_type: {
			type: 'string'
		}
	},
	type: 'object',
	required: ['access_token', 'token_type']
} as const;

export const $TrackCreate = {
	properties: {
		media_url: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255
				},
				{
					type: 'null'
				}
			],
			examples: ['https://www.imageurl.com/example_post.jpg']
		},
		isrc: {
			type: 'string',
			maxLength: 255,
			examples: ['QZWDD2467025']
		},
		iswc: {
			type: 'string',
			maxLength: 255
		},
		track_name: {
			type: 'string',
			maxLength: 255,
			examples: ['Here Comes the Sun']
		},
		track_version: {
			type: 'string',
			maxLength: 255,
			examples: ['Remixes']
		},
		birthdate: {
			type: 'string',
			format: 'date',
			examples: ['1940-10-09']
		},
		phone: {
			type: 'string',
			maxLength: 255,
			examples: ['+1 (555) 555-5555']
		},
		birth_location: {
			type: 'string',
			maxLength: 255,
			examples: ['New York, NY']
		},
		current_location: {
			type: 'string',
			maxLength: 255,
			examples: ['Los Angeles, CA']
		},
		track_biography: {
			type: 'string',
			maxLength: 1500,
			examples: ['This is the biography of an example track.']
		},
		track_website: {
			type: 'string',
			maxLength: 255,
			examples: ['https://www.exampletrack.com/']
		},
		spotify_uri: {
			type: 'string',
			maxLength: 255,
			examples: ['https://open.spotify.com/track/123456789']
		},
		apple_music_uri: {
			type: 'string',
			maxLength: 255,
			examples: ['https://music.apple.com/us/track/exampletrack/123456789']
		},
		youtube_url: {
			type: 'string',
			maxLength: 255,
			examples: ['https://www.youtube.com/channel/exampletrack']
		},
		primary_genre_id: {
			type: 'string',
			format: 'uuid'
		},
		primary_subgenre_id: {
			type: 'string',
			format: 'uuid'
		}
	},
	additionalProperties: false,
	type: 'object',
	required: [
		'isrc',
		'iswc',
		'track_name',
		'track_version',
		'birthdate',
		'phone',
		'birth_location',
		'current_location',
		'track_biography',
		'track_website',
		'spotify_uri',
		'apple_music_uri',
		'youtube_url',
		'primary_genre_id',
		'primary_subgenre_id'
	]
} as const;

export const $TrackUpdate = {
	properties: {
		media_url: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255
				},
				{
					type: 'null'
				}
			],
			examples: ['https://www.imageurl.com/example_post.jpg']
		},
		isrc: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255
				},
				{
					type: 'null'
				}
			],
			examples: ['QZWDD2467025']
		},
		iswc: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255
				},
				{
					type: 'null'
				}
			]
		},
		track_name: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255
				},
				{
					type: 'null'
				}
			],
			examples: ['Here Comes the Sun']
		},
		track_version: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255
				},
				{
					type: 'null'
				}
			],
			examples: ['Remixes']
		},
		birthdate: {
			anyOf: [
				{
					type: 'string',
					format: 'date'
				},
				{
					type: 'null'
				}
			],
			examples: ['1940-10-09']
		},
		phone: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255
				},
				{
					type: 'null'
				}
			],
			examples: ['+1 (555) 555-5555']
		},
		birth_location: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255
				},
				{
					type: 'null'
				}
			],
			examples: ['New York, NY']
		},
		current_location: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255
				},
				{
					type: 'null'
				}
			],
			examples: ['Los Angeles, CA']
		},
		track_biography: {
			anyOf: [
				{
					type: 'string',
					maxLength: 1500
				},
				{
					type: 'null'
				}
			],
			examples: ['This is the biography of an example track.']
		},
		track_website: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255
				},
				{
					type: 'null'
				}
			],
			examples: ['https://www.exampletrack.com/']
		},
		spotify_uri: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255
				},
				{
					type: 'null'
				}
			],
			examples: ['https://open.spotify.com/track/123456789']
		},
		apple_music_uri: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255
				},
				{
					type: 'null'
				}
			],
			examples: ['https://music.apple.com/us/track/exampletrack/123456789']
		},
		youtube_url: {
			anyOf: [
				{
					type: 'string',
					maxLength: 255
				},
				{
					type: 'null'
				}
			],
			examples: ['https://www.youtube.com/channel/exampletrack']
		},
		primary_genre_id: {
			anyOf: [
				{
					type: 'string',
					format: 'uuid'
				},
				{
					type: 'null'
				}
			]
		},
		primary_subgenre_id: {
			anyOf: [
				{
					type: 'string',
					format: 'uuid'
				},
				{
					type: 'null'
				}
			]
		}
	},
	additionalProperties: false,
	type: 'object'
} as const;

export const $ValidationError = {
	properties: {
		loc: {
			items: {
				anyOf: [
					{
						type: 'string'
					},
					{
						type: 'integer'
					}
				]
			},
			type: 'array'
		},
		msg: {
			type: 'string'
		},
		type: {
			type: 'string'
		}
	},
	type: 'object',
	required: ['loc', 'msg', 'type']
} as const;
